#!/usr/bin/env bash
# Fixes Apache so that it returns "Hello Holberton" and confirms it's running

apt-get update -y
apt-get install -y apache2

echo "Hello Holberton" > /var/www/html/index.html

service apache2 restart

echo "apache2 is running"
