#!/usr/bin/env bash
# Installs and configures HAproxy on a new Ubuntu machine to load balance between web-01 and web-02

export DEBIAN_FRONTEND=noninteractive

apt-get update -y
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 6927-web-01 44.203.195.131:80 check
    server 6927-web-02 13.222.52.30:80 check
EOF

haproxy -c -f /etc/haproxy/haproxy.cfg
service haproxy restart
