#!/usr/bin/env bash
# Installs and configures HAProxy to load balance between web-01 and web-02

apt update && apt install haproxy -y

cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
    log /dev/log local0
    maxconn 2000
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 172.25.0.11:80 check
    server web-02 172.25.0.12:80 check
HAPROXY

service haproxy start
