#!/usr/bin/env bash
# Installs and configures nginx to return "Holberton School for the win!"

sudo apt-get update -y
sudo apt-get install -y nginx
sudo sh -c 'echo "Holberton School for the win!" > /var/www/html/index.html'
sudo service nginx restart
