#!/usr/bin/env bash
# Installs and configures Nginx so it serves Holberton School at /

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.html
service nginx restart
